build:
  image: teaci/msys$$arch:testing
  shell: msys$$arch
  pull: true
  commands:
    - echo 'Prepare'
    - git config --global user.email "teaci@users.noreply.github.com"
    - git config --global user.name "Tea CI"

    - echo 'Testing MSYS2 zlib package'
    - svn co https://github.com/Alexpux/MSYS2-packages/trunk/zlib
    - cd zlib
    - makepkg --noconfirm --noprogressbar --skippgpcheck --nocheck --syncdeps --rmdeps --cleanbuild
    - cd ..

    - echo 'Testing msys2-runtime package'
    - svn co https://github.com/Alexpux/MSYS2-packages/trunk/msys2-runtime
    - cd msys2-runtime
    - makepkg --noconfirm --noprogressbar --skippgpcheck --nocheck --syncdeps --rmdeps --cleanbuild
    - cd ..

    - echo 'Testing MinGW zlib package'
    - svn co https://github.com/Alexpux/MINGW-packages/trunk/mingw-w64-zlib
    - cd mingw-w64-zlib
    - makepkg-mingw --noconfirm --noprogressbar --skippgpcheck --nocheck --syncdeps --rmdeps --cleanbuild
    - cd ..

    - echo 'All test passed'
    - echo 'Clone teaci/msys$$arch:testing to teaci/msys$$arch:latest using drone docker plugin...'

notify:
  gitter:
    webhook: https://webhooks.gitter.im/e/d8f2032e40a8e78a3882

publish:
  docker:
    file: Dockerfile.$$arch
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/msys$$arch # dockerhub repo, don't confused with github repo.
    tag:
      - "latest"
      - "w1.9.10-m2.5.1-4r"
    when:
      repo: TeaCI/msys2-docker # case sensitive
      branch: release # only build latest tag in release branch.

matrix:
  arch:
    - 64
    - 32
