build:
  image: drone/golang:1.5
  commands:
    - echo 'Build teaci/msys32:testing image using drone docker plugin...'

notify:
  irc:
    prefix: build
    nick: msys32-docker
    channel: wine-ci
    server:
      host: chat.freenode.net
      port: 6667

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/msys32
    tag:
      - "testing"
      - "w1.9.10-m2.5.1-1"
    when:
      repo: TeaCI/msys32-docker # case sensitive
      branch: master
