build:
  image: teaci/mingw32:testing
  shell: msys32
  pull: true
  commands:
    - echo 'Testing MSYS2 zlib package'
    - svn co https://github.com/Alexpux/MSYS2-packages/trunk/zlib
    - cd zlib
    - makepkg --noconfirm --noprogressbar --skippgpcheck --nocheck --syncdeps --rmdeps --cleanbuild
    - cd ..
    - echo 'All test passed'
    - echo 'Clone teaci/mingw32:testing to teaci/msys32:latest using drone docker plugin...'

notify:
  irc:
    prefix: build
    nick: mingw32-docker
    channel: wine-ci
    server:
      host: chat.freenode.net
      port: 6667

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/msys32 # dockerhub repo, don't confused with github repo.
    tag:
      - "latest"
    when:
      repo: TeaCI/mingw32-docker # case sensitive
      branch: msys32 # only build msys32 image in msys32 branch.
