build:
  image: drone/golang:1.5
  commands:
    - echo 'Build teaci/mingw32 image using drone docker plugin...'

notify:
  irc:
    prefix: build
    nick: mingw32-docker
    channel: wine-ci
    server:
      host: chat.freenode.net
      port: 6667

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: teaci/mingw32
    tag:
      - "latest"
      - "w1.9.5-m2.5.0-6"
    when:
      repo: TeaCI/mingw32-docker # case sensitive
      branch: master
